#!/usr/bin/env bash
# this script transfers a file to a server

if [ "$#"- lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file=$1
serverIp=$2
usename=$3
sshKey=$4

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$sshKey" "$file" "$username@$serverIp:~/"

