#!/usr/bin/env bash
# Configure a new Ubuntu machine with HAproxy load balancer

# Update package list and install required packages
sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common

# Add HAproxy PPA, update package lists with new PPA and install HAproxy
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get install -y haproxy

# Define HAproxy configuration
conf="\
frontend tiana-frontend
    bind *:80
    mode http
    timeout client 30s
    default_backend tiana-backend

backend tiana-backend
    balance roundrobin
    mode http
    timeout connect 5s
    timeout server 30s
    server 297641-web-01 54.175.227.244:80 check
    server 297641-web-02 54.197.129.188:80 check
"
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$conf" | sudo tee /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo systemctl restart haproxy
