#!/usr/bin/env bash
# Configure a new Ubuntu machine with HAproxy load balancer

# Update package list and install required packages
sudo apt-get -y update
sudo apt-get install -y --no-install-recommends software-properties-common

# Add HAproxy PPA and install HAproxy
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get install -y haproxy

# Define HAproxy configuration
conf="\
frontend hypotherm-frontend
    bind *:80
    mode http
    default_backend hypotherm-backend

backend hypotherm-backend
    balance roundrobin
    server 297641-web-01 54.175.227.244:80 check
    server 297641-web-02 54.197.129.188:80 check
"
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$conf" | sudo tee /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo systemctl enable haproxy
sudo systemctl restart haproxy
