#!/usr/bin/env bash
#ping a network a 5 times

if [$# -lt 1]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
input=$1
if [[ ! $input =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
then
	exit 1
fi
ping -c 5 "$input"

