#!/usr/bin/env bash
#this script shows  all active IPv4 IPs on the machine it’s executed on
ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 6-
#the ouput of ifconfig is piped to grep which is used in conjunction with regexp to search
